### ISSUE TITLE
Top-level functions that react to tile actions must be marked as vm:entry-point to run in release mode

### ISSUE THREAD

**Issue by ovchars2** [Apparence-io/quick_settings#1]
I am trying to run the app in release mode. It is built with Flutter 3.7.0
When I am running the app in debug mode, initialization that is proposed in docs, works as a charm.

But, when the app is running in release mode, I am getting errors:
 ```
E/flutter: [ERROR:flutter/lib/ui/dart_runtime_hooks.cc(38)] Dart Error: Unhandled exception:
    NoSuchMethodError: No top-level getter '_onTileClicked' declared.
    Receiver: top-level
    Tried calling: _onTileClicked
```

`QuickSettings.setup()` is called directly from `main()`,  `_onTileClicked` and other functions are top-level.
Issue is resolved when i add `@pragma('vm:entry-point')` above each of the functions:
```
@pragma('vm:entry-point')
Tile? _onTileClicked(Tile tile) {
// do something here
}
```
I am not sure how this initialization can be avoided, but it would be helpful to at least see this part of the configuration in the docs

**Comment by apalala-dev** [comment]
I've added documentation on this annotation in PR #3.
Feel free to take a look  👍

**Comment by apalala-dev** [comment]
The documentation is added as part of the 1.0.1 release available now on [pub.dev](https://pub.dev/packages/quick_settings).
